# Save as .codeclimate.yml (note leading .) in project root directory
# languages:
#   Ruby: true
#   JavaScript: true
exclude_paths:
  - test/**/*
  - vendor/**/*

# For a list of all available engines, see here:
# http://docs.codeclimate.com/article/296-engines-available-engines

engines:
# to turn on an engine, add it here and set enabled to `true`
# to turn off an engine, set enabled to `false` or remove it
  rubocop:
    enabled: true
  # golint:
  #   enabled: true
  # gofmt:
  #   enabled: true
  # eslint:
  #   enabled: true
  # csslint:
  #   enabled: true

# Engines can analyze files and report issues on them, but you can separately
# decide which files will receive ratings based on those issues. This is
# specified by path patterns under the ratings key.

# For more details see here:
# http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml#platform

# ratings:
#   paths:
#   - app/**
#   - lib/**
#   - "**.rb"
#   - "**.go"

# You can globally exclude files from being analyzed by any engine using the
# exclude_paths key.

#exclude_paths:
#- spec/**/*
#- vendor/**/*
